Repository eBay/ebayui-core, pull requests merged in 2018-08, with the labels that each got.

#305 Merge 0.8.0 milestone branch into master prior to release
  .babelrc
  demo/index.js
  demo/template.marko
  marko.json
  package.json
  src/components/ebay-button/index.js
  src/components/ebay-button/test/test.browser.js
  src/components/ebay-carousel/README.md
  src/components/ebay-carousel/examples/01-continuous/template.marko
  src/components/ebay-carousel/examples/02-starting-index/template.marko
  src/components/ebay-carousel/examples/03-few-items/template.marko
  src/components/ebay-carousel/examples/04-variable-width-items/template.marko
  src/components/ebay-carousel/examples/05-single-item-per-slide/template.marko
  src/components/ebay-carousel/examples/06-starting-slide/template.marko
  src/components/ebay-carousel/examples/07-two-items-per-slide/template.marko
  src/components/ebay-carousel/examples/08-three-items-per-slide/template.marko
  src/components/ebay-carousel/examples/09-accessibility-text/template.marko
  src/components/ebay-carousel/examples/10-autoplay/template.marko
  src/components/ebay-carousel/index.js
  src/components/ebay-carousel/style-touch.less
  src/components/ebay-carousel/style.less
  src/components/ebay-carousel/template.marko
  src/components/ebay-carousel/test/test.browser.js
  src/components/ebay-carousel/test/test.server.js
  src/components/ebay-carousel/utils/on-scroll-end/index.js
  src/components/ebay-carousel/utils/scroll-transition/index.js
  src/components/ebay-dialog/index.js
  src/components/ebay-dialog/template.marko
  src/components/ebay-dialog/test/test.browser.js
  src/components/ebay-icon/symbols/pause.marko
  src/components/ebay-icon/symbols/play.marko
  src/components/ebay-menu/README.md
  src/components/ebay-menu/examples/08-no-label/template.marko
  src/components/ebay-menu/examples/09-icon-with-text-label/template.marko
  src/components/ebay-menu/examples/10-icon-label-with-toggle/template.marko
  src/components/ebay-menu/examples/11-icon-label-without-toggle/template.marko
  src/components/ebay-menu/examples/12-radio/template.marko
  src/components/ebay-menu/examples/13-checkbox/template.marko
  src/components/ebay-menu/index.js
  src/components/ebay-menu/mock/index.js
  src/components/ebay-menu/template.marko
  src/components/ebay-menu/test/test.server.js
  src/components/ebay-menu/transformer.js
  yarn.lock
Labels: squash: NO thanks

#274 Textbox component
  README.md
  demo/browser.json
  marko.json
  src/components/ebay-textbox/README.md
  src/components/ebay-textbox/browser.json
  src/components/ebay-textbox/examples/01-default/template.marko
  src/components/ebay-textbox/examples/02-disabled/template.marko
  src/components/ebay-textbox/examples/03-placeholder/template.marko
  src/components/ebay-textbox/examples/04-invalid/template.marko
  src/components/ebay-textbox/examples/05-fluid/template.marko
  src/components/ebay-textbox/examples/06-multiline/template.marko
  src/components/ebay-textbox/examples/07-multiline-disabled/template.marko
  src/components/ebay-textbox/examples/08-multline-invalid/template.marko
  src/components/ebay-textbox/index.js
  src/components/ebay-textbox/template.marko
  src/components/ebay-textbox/test/test.server.js
Labels: sprint: 13

#362 Pagination: fix responsive behavior
  src/components/ebay-pagination/index.js
  src/components/ebay-pagination/mock/index.js
  src/components/ebay-pagination/test/test.browser.js
Labels: component: pagination, semver: patch, squash: YES please, type: enhancement
